version: '3'

services:

  #PostgreSQL Service
  db:
    image: postgres:11.1-alpine
    container_name: nabby_node_postgresql
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
      - '${POSTGRESQL_PORT}:${POSTGRESQL_PORT}'
    volumes:
      - ./docker/postgres/:/docker-entrypoint-initdb.d/
    networks:
      - api-network

  #Node Service
  app:
    image: "node:14-alpine"
    container_name: nabby_node_app
    restart: unless-stopped
    tty: true
    working_dir: /app
    env_file: .env
    ports:
      - ${NODE_PORT}:${NODE_PORT}
    volumes:
      - ./:/app
    links:
      - db
    depends_on:
      - db
    networks:
      - api-network

#Docker Networks
networks:
  api-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local